/*
 * Copyright (C) 2014 Joos Kiener <Joos.Kiener@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package io.github.kienerj.sdf_viewer;

import java.awt.Cursor;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Objects;
import java.util.Properties;
import javax.swing.*;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileSystemView;
import lombok.Getter;
import lombok.Setter;
import io.github.kienerj.sdf_reader.SdfReader;
import org.slf4j.ext.XLogger;
import org.slf4j.ext.XLoggerFactory;

/**
 *
 * @author Joos Kiener <Joos.Kiener@gmail.com>
 */
public class SdfViewer extends javax.swing.JFrame {

    private static final XLogger logger = XLoggerFactory.getXLogger("SdfViewer");
    private static final String SETTINGS_FILE = "FreeSdfViewer.properties";
    private SdfReader sdfReader;
    @Getter
    @Setter
    private File lastOpenDir;
    private File settingsDir;
    private Boolean keepIndex = false;

    /**
     * Creates new form SdfViewer
     */
    public SdfViewer() {
        // save settingsFile on shutdown
        addShutdownHook();
        //determine directory of settings
        // local app data for windows else same dir as this executable jar.
        setSettingsDir();
        // load settings
        loadSettings();

        initComponents();
        saveIndexMenuItem.setState(keepIndex);
        fileChooser.setAcceptAllFileFilterUsed(false);
        FileFilter sdfFileFilter = new SdfFileFilter();
        fileChooser.setFileFilter(sdfFileFilter);
        if (lastOpenDir != null) {
            fileChooser.setCurrentDirectory(lastOpenDir);
        }
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JMenuBar jMenuBar1 = new JMenuBar();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        JMenu jMenu1 = new JMenu();
        JMenuItem loadFileMenuItem = new JMenuItem();
        JMenu jMenu2 = new JMenu();
        saveIndexMenuItem = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Free SDF Viewer");
        setAutoRequestFocus(false);

        jScrollPane1.setViewportView(jTable1);

        jMenu1.setText("File");

        loadFileMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        loadFileMenuItem.setText("Load SD-File...");
        loadFileMenuItem.addActionListener(this::loadFileMenuItemActionPerformed);
        jMenu1.add(loadFileMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Settings");

        saveIndexMenuItem.setSelected(true);
        saveIndexMenuItem.setText("Save Index");
        saveIndexMenuItem.addActionListener(this::saveIndexMenuItemActionPerformed);
        jMenu2.add(saveIndexMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileMenuItemActionPerformed

        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            logger.debug("Opening SD-File '{}'.", file.getAbsoluteFile());
            SdfLoader loader = new SdfLoader(this, file);
            loader.execute();
        } else {
            logger.debug("Opening of SD-file cancelled by the user.");
        }
    }//GEN-LAST:event_loadFileMenuItemActionPerformed

    private void saveIndexMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveIndexMenuItemActionPerformed
        keepIndex = saveIndexMenuItem.getState();
        if (sdfReader != null) {
            sdfReader.setSaveIndex(keepIndex);
        }
    }//GEN-LAST:event_saveIndexMenuItemActionPerformed

    private void addShutdownHook() {
        Runtime.getRuntime().addShutdownHook(new Thread() {
            SdfViewer viewer;

            @Override
            public void run() {
                viewer.saveSettings();
            }

            private Thread init(SdfViewer viewer) {
                this.viewer = viewer;
                return this;
            }
        }.init(this));
    }

    private void setSettingsDir() {
        String OS = (System.getProperty("os.name")).toUpperCase();
        if (OS.contains("WIN")) {
            // save settings in appdata
            settingsDir = new File(System.getenv("LOCALAPPDATA")
                    + "/FreeSdfViewer");
            if (!settingsDir.exists()) {
                boolean success = settingsDir.mkdir();
                if (!success) {
                    // directory were this jar file is stored
                    // use it to save settings to same dir.
                    settingsDir = new File(Objects.requireNonNull(ClassLoader.getSystemClassLoader()
                            .getResource(".")).getPath());
                }
            }
        } else {
            // directory were this jar file is stored
            // use it to save settings to same dir.
            settingsDir = new File(Objects.requireNonNull(ClassLoader.getSystemClassLoader()
                    .getResource(".")).getPath());
        }
    }

    private void saveSettings() {
        Properties properties = new Properties();

        if (lastOpenDir != null) {
            properties.put("lastOpenDir", lastOpenDir.getPath());
        }
        properties.put("keepIndex", keepIndex.toString());

        try (FileOutputStream out = new FileOutputStream(settingsDir + "/" + SETTINGS_FILE)) {
            properties.store(out, null);
        } catch (IOException ex) {
            logger.error("Failed to save settings:");
            logger.catching(ex);
        }
    }

    private void loadSettings() {
        Properties settings = new Properties();
        File settingsFile = new File(settingsDir + "/" + SETTINGS_FILE);
        if (settingsFile.exists()) {
            try (FileInputStream in = new FileInputStream(settingsFile)) {
                settings.load(in);
                FileSystemView fw = fileChooser.getFileSystemView(); // for default open directory
                String lastOpenDirPath = settings.getProperty("lastOpenDir", fw.getDefaultDirectory().toString());
                lastOpenDir = new File(lastOpenDirPath);
                if (!lastOpenDir.exists()) {
                    lastOpenDir = null;
                }
                String keepIndexSetting = settings.getProperty("keepIndex", keepIndex.toString());
                keepIndex = Boolean.valueOf(keepIndexSetting);
            } catch (IOException ex) {
                logger.error("Failed to load settings:");
                logger.catching(ex);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {//
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SdfViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SdfViewer().setVisible(true));
    }

    private class SdfLoader extends SwingWorker<JTable, Void> {

        private final JFrame frame;
        private final File sdFile;
        private JTable table;
        private IOException ioException;

        public SdfLoader(JFrame frame, File sdFile) {
            this.frame = frame;
            frame.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            this.sdFile = sdFile;
        }

        @Override
        public JTable doInBackground() {
            try {
                //close old file
                if (sdfReader != null) {
                    sdfReader.close();
                }
                sdfReader = new SdfReader(sdFile, keepIndex);
                lastOpenDir = sdFile.getParentFile();
                table = new SdfTable(jScrollPane1, sdfReader, 200);
            } catch (IOException ex) {
                logger.catching(ex);
                ioException = ex;
                table = jTable1;
            }
            return table;
        }

        @Override
        public void done() {
            if (ioException == null) {
                jTable1 = table;
                jScrollPane1.setViewportView(table);
                frame.setCursor(Cursor.getDefaultCursor());
            } else {
                JOptionPane.showMessageDialog(SdfViewer.this,
                        ioException.getMessage(),
                        "Error opening file",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    private final JFileChooser fileChooser = new JFileChooser();
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JCheckBoxMenuItem saveIndexMenuItem;
    // End of variables declaration//GEN-END:variables
}
